### ISSUE TITLE
Rename crossplane-function-cue to function-cue

### ISSUE THREAD

**Issue by gotwarlost** [crossplane-contrib/function-cue#2]
Need to:

* rename the existing function-cue repo to function-cue-archived and archive it (@Mitsuwa )
* rename the current repo to function-cue. I think I have access to do this.
* set up the `XPKG_ACCESS_ID` and `XPKG_TOKEN` secrets for the repo. Not sure where these come from. (@negz)
* decide on the tag we should use for the first version of the new code. Examples in function-cue have `mitsuwa/function-cue:v0.1.2` and latest tag in the elastic repo is `v0.1.9`. So I propose `v0.2.0` as the first tag for this function.
* ensure code coverage works on mainline builds and shows the correct badges

**Comment by negz** [comment]
I can setup the access ID and tokens - they need admin access to the crossplane-contrib org at https://marketplace.upbound.io per https://github.com/crossplane/docs/issues/785.

**Comment by negz** [comment]
The tokens are setup. I think you'll need to copy a typical `ci.yml` into the repo for pushing to xpkg.upbound.io to work.

https://github.com/crossplane/function-template-go/blob/main/.github/workflows/ci.yml
